node('nodejs8') {
  stage 'checkout'
    checkout scm
  stage 'build'
  sh '''
    pwd
    ls -l
    npm install -d
    $(npm bin)/ng build
    oc start-build angular-5-example --from-dir=. --follow
  '''
}
