node('nodejs8') {
  stage ('checkout') {
    checkout scm
  }
  stage ('install modules'){
    sh '''
      npm install --verbose -d 
      npm install --save classlist.js
    '''
  }
  stage ('test') {
    sh '''
      ls -l /opt/google/chrome/chrome-sandbox
      $(npm bin)/ng test --single-run
    '''
  }
  stage ('build') {
    sh '''
      $(npm bin)/ng build --prod --build-optimizer
      mkdir dist/nginx-cfg
      cp nginx/status.conf dist/nginx-cfg
      oc start-build angular-5-example-rhel --from-dir=dist --follow
    '''
  }
}
